### ISSUE TITLE
Cannot request a Json-based representation of @obsels when at least one obsel of the trace contains multiple JSON-LD @type

### ISSUE THREAD

**Issue by StatelessCat** [ktbs/ktbs#50]
Steps to reproduce:

POST 
```
{
  "@context": [
    "http://liris.cnrs.fr/silex/2011/ktbs-jsonld-context",
    { "m": "http://localhost:8001/base1/m1#" }
  ],
  "@id": "http://localhost:8001/base1/t1/obs1",
  "hasTrace": "./",
  "begin": 1462784265154,
  "end": 1462784265154,
  "@type": "m:xapiStatement"
}
```
```curl -vv http://localhost:8001/base1/t1/@obsels -H "Accept: application/ld+json"``` -> OK

-----------------------------
POST
```
{
  "@context": [
    "http://liris.cnrs.fr/silex/2011/ktbs-jsonld-context",
    { "m": "http://localhost:8001/base1/m1#" }
  ],
  "@id": "http://localhost:8001/base1/t1/obs1",
  "hasTrace": "./",
  "begin": 1462784265154,
  "end": 1462784265154,
  "@type": ["m:xapiStatement", "http://semweb.mmlab.be/ns/tincan2prov/Statement"]
}
```
```curl -vv http://localhost:8001/base1/t1/@obsels -H "Accept: application/ld+json"``` -> NON-OK
Trace: 
```
127.0.0.1 - - [09/May/2016 11:15:05] "GET /base1/t1/@obsels HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/serpar/jsonld_serializers.py", line 39, in wrapped
    for i in func(*args, **kw):
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/serpar/jsonld_serializers.py", line 777, in serialize_json_trace_obsels
    tobsels_dict = trace_obsels_to_json(graph, tobsels, bindings)
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/serpar/jsonld_serializers.py", line 701, in trace_obsels_to_json
    obs_dict['additionalType'].append(valconv_uri(other))
AttributeError: 'NoneType' object has no attribute 'append'
127.0.0.1 - - [09/May/2016 11:15:05] "GET /base1/t1/@obsels HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 36110)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```
I'm using the `git branch:  develop \n commit:  db62930bde3ac253079766090bd837bb2669d83d`.

Do you think there is anything wrong with my JSON-LD Obsel that is causing the bug to happen ? 
Thanks.
Raphaël.

**Comment by pchampin** [comment]
Note that, with this fix, ``@type`` in obsels may now contain an array of URIs if there are several types.

I was first tempted to keep a single value in ``@type`` and put additional types in the ``additionalType`` key (as for other classes of resources in kTBS), but the problem is that there is no simple way to decide on which type to keep as the "main" type.

So I applied the Zen of Python:

> In the face of ambiguity, refuse the temptation to guess.

**Comment by StatelessCat** [comment]
Thanks for this fix and the answer. 

A good point for this fix, in my opinion, is that this behavior is consistent against other serialisations like Turtle. 

I had not thought about the question of what is the "main" type of an Obsel.
At what point this could be problematic ?
Only if an Obsel is defined having multiples ObselTypes ?

**Comment by pchampin** [comment]
> A good point for this fix, in my opinion, is that this behavior is consistent against other serialisations like Turtle.

Yes, but on the other hand it is inconsistent with the JSON-LD serialization of other elements of kTBS. For example, if a Base has other types (e.g. ``ex:SensibleContent``), the JSON will be:
```json
  { "@id": "my-base", "@type": "Base", "additionalType": ["ex:SensibleContent"] }
```

> I had not thought about the question of what is the "main" type of an Obsel.

That's the problem, indeed, and that's why I decided to treat obsels differently from other elements...
(in fact, to be absolutely consistent, the ``@type`` would have to be ``Obsel``, and all other types would have to be in ``additionalType``, but that would not be a very useful change...)

> At what point this could be problematic ?
> Only if an Obsel is defined having multiples ObselTypes ?

I don't like the fact that ``@type`` contains sometimes a single value, and sometimes an array. This forces you to test which kind it is every time you are getting its value (at least, if you want your code to work in every possible case).

Another solution would have been to decide that the ``@type`` of obsels always hold an array, even if it contains a single value, but that seems a little cumbersome.
