### ISSUE TITLE
Builtin methods URIs should respond to GET requests

### ISSUE THREAD

**Issue by hsaladin** [ktbs/ktbs#79]
When sending a GET request to the URI of a builtin method, kTBS replies with a "404 - Not found" error, unlike when querying a user method which returns a normal response.
As there is no clear distinction between user and builtin methods, it is difficult to handle them differently without writing some dirty code.

Builtin methods should respond to GET requests the same way that user methods do.

**Comment by pchampin** [comment]
The method-related properties (`hasMethod`, `hasParentMethod` and `hasBuiltinMethod`) must be interpreted with caution: their value is *not always* a relative URI. For convenience, a number of "aliases" exist for the standard built-in methods ("filter", "fsa", "fusion", "hrules", "isparql", "parallel", "pipe", "sparql"). Those should be interpreted as prefixed with http://liris.cnrs.fr/silex/2009/ktbs#, and they *do* refer to a description in Turle (not in JSON for the moment, unfortunately).

The quick and dirty solution is to hard-code the list of exceptions in your program, and handle them as special cases.

The cleanest solution is to use a JSON-LD processor to transform the JSON you get into the JSON you would rather work with (in that case, keep it the same except for those "aliases", which could be translated into their absolute URI). I can help with this solution if you want to go that way.

An intermediate solution is to inspect the `@context` in the JSON you get, to dynamically know the list of exceptions (instead of hard-coding it), but still handle them as a special case.
