### ISSUE TITLE
CORS headers not sent in some cases

### ISSUE THREAD

**Issue by hsaladin** [ktbs/ktbs#80]
CORS headers are not included in some server's responses.
This makes it impossible to read the response's data from a JavaScript application running in a browser and hosted on a different server.

Cases where CORS headers are not sent include (non-exhaustive list) :
- the server responds with an error (404, 500 ...)
- the server requires authentication (401)

All responses should include CORS headers, even errors, so a 3rd-party client can handle them properly.

**Comment by pchampin** [comment]
Darn, I would have sworn this had already been fixed :-/

**Comment by hsaladin** [comment]
I realize now that you might be right ... only the servers I'm working with may be not up to date with the latest release ! (sorry)
Anyway : I need to implement authentication, but the only example of restricted-access kTBS instance that I know of (Hubble) doesn't provide CORS when it replies with a 401.

**Comment by pchampin** [comment]
So I checked and indeed, this had already been solved in most cases (i.e., all 4xx errors raised by kTBS itself).  I can not guarantee that 5xx errors will always contain the CORS headers, because by definition, 5xx errors mean that the server does not behave as expected!...

Regarding authentication, the problem you have is slightly different: the 401 error is *not* returned by kTBS, but by Apache, before kTBS even gets the request. That is why you do not get CORS headers.

This advocates for handling authentication inside kTBS rather than delegating ot to Apache... But that will be a different issue.
